### ISSUE TITLE
It does not autoscale

### ISSUE THREAD

**Issue by SamyOteroGlez** [jcwimer/docker-swarm-autoscaler#1]
Hello,

I am using your solution but it does not autoscale the container. I defined a minimum of 3 replicas and a maximum of 4, but when the container starts it only shows 1.

Please check below my stach.yml files

My container
```
version: '3.3'
services:
  plex:
    image: linuxserver/plex:latest
    environment:
      PGID: '1000'
      PUID: '1000'
      UMASK_SET: '022'
      VERSION: docker
    ports:
     - 32400:32400
    volumes:
     - /home/tesa/plex/volumes/config:/config
     - /home/tesa/plex/volumes/transcode:/trascode
     - /media/tesa/6849030A04871840:/external
    networks:
     - default
     - autoscale_autoscale
    logging:
      driver: json-file
    deploy:
      labels:
        swarm.autoscaler: 'true'
        swarm.autoscaler.maximum: '4'
        swarm.autoscaler.minimum: '3'
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.role == manager
networks:
  autoscale_autoscale:
    external: true
  default:
    driver: overlay
```

The autoscaler:
```
version: '3.3'
services:
  cadvisor:
    image: google/cadvisor:v0.25.0
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /:/rootfs
     - /var/run:/var/run
     - /sys:/sys
     - /var/lib/docker/:/var/lib/docker
    networks:
     - autoscale
    logging:
      driver: json-file
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.1'
          memory: 64M
        limits:
          cpus: '0.1'
          memory: 128M
  docker-swarm-autoscaler:
    image: jcwimer/docker-swarm-autoscaler:latest
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - autoscale
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.1'
          memory: 64M
        limits:
          cpus: '0.1'
          memory: 128M
  prometheus:
    image: jcwimer/prometheus-swarm-autoscaler:latest
    command:
     - --storage.tsdb.retention
     - 1d
     - --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
    networks:
     - autoscale
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.5'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 1024M
networks:
  autoscale:
    driver: overlay
```

Thanks in advance.

Sam
