### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by justlife4x4** [jcwimer/docker-swarm-autoscaler#8]
Hii,
My `docker-compose.yml` looks kinda like this 

```
version: '3.9'
services:
  api:
    container_name: hotelapp_api
    build: .
    ports:
      - 4000:4000
      - 4001:4001
      # - 27017:27017
      # - 6379:6379
      # - 587:587
    environment:
      - Env='Values'
    deploy:
      resources:
        limits:
          memory: "1g"      # 1 GB RAM
          cpus: "1.0"       # 1 vCPU
```

How to implement it?
